import Foundation

// MARK: - Sandbox Drive Manager
//
// Manages isolated WINEPREFIX directories for each game.
// All game data lives within the app's iOS sandbox (Documents directory).
// Each game gets its own virtual C:\ drive with proper Wine directory structure.

class SandboxDrive {

    // MARK: - Resolve Paths

    /// Get the full sandbox path for a game's data directory
    static func resolveGamePath(for game: GameEntry) -> String {
        let docs = documentsDirectory()
        let safeName = game.title
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: ":", with: "")
        return "\(docs)/SteamLibrary/\(safeName)"
    }

    /// Get the WINEPREFIX path for a game
    static func resolvePrefixPath(for game: GameEntry) -> String {
        return "\(resolveGamePath(for: game))/prefix"
    }

    // MARK: - Create Game Container

    /// Set up the full directory structure for a new game installation
    static func createGameContainer(for game: GameEntry) throws {
        let gamePath = resolveGamePath(for: game)
        let prefixPath = resolvePrefixPath(for: game)
        let fm = FileManager.default

        let directories = [
            gamePath,
            "\(gamePath)/game_files",           // Raw game files from Steam
            "\(gamePath)/translated_arm64",      // AOT-translated ARM64 binaries
            "\(gamePath)/saves",                 // Save data (backed up separately)
            prefixPath,                          // WINEPREFIX root
            "\(prefixPath)/drive_c",
            "\(prefixPath)/drive_c/windows",
            "\(prefixPath)/drive_c/windows/system32",
            "\(prefixPath)/drive_c/windows/syswow64",
            "\(prefixPath)/drive_c/users",
            "\(prefixPath)/drive_c/users/steampad",
            "\(prefixPath)/drive_c/users/steampad/AppData",
            "\(prefixPath)/drive_c/users/steampad/AppData/Local",
            "\(prefixPath)/drive_c/users/steampad/AppData/Roaming",
            "\(prefixPath)/drive_c/users/steampad/Documents",
            "\(prefixPath)/drive_c/Program Files",
            "\(prefixPath)/drive_c/Program Files (x86)",
        ]

        for dir in directories {
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }

        // Write Wine system.reg (minimal Windows 10 configuration)
        let systemReg = """
        WINE REGISTRY Version 2
        ;; Generated by SteamPad

        [System\\\\CurrentControlSet\\\\Control\\\\Windows]
        "CSDVersion"=dword:00000000

        [Software\\\\Microsoft\\\\Windows NT\\\\CurrentVersion]
        "CurrentVersion"="10.0"
        "ProductName"="Windows 10 Pro"
        "CurrentBuild"="19041"
        "CurrentBuildNumber"="19041"
        """
        try systemReg.write(toFile: "\(prefixPath)/system.reg", atomically: true, encoding: .utf8)

        print("[Sandbox] Created container for \(game.title) at \(gamePath)")
    }

    // MARK: - Storage Info

    /// Get the total disk usage for a game container
    static func diskUsage(for game: GameEntry) -> Int64 {
        let path = resolveGamePath(for: game)
        return directorySize(at: path)
    }

    /// Get total available disk space on the device
    static func availableSpace() -> Int64 {
        let url = URL(fileURLWithPath: documentsDirectory())
        let values = try? url.resourceValues(forKeys: [.volumeAvailableCapacityForImportantUsageKey])
        return values?.volumeAvailableCapacityForImportantUsage ?? 0
    }

    // MARK: - Cleanup

    /// Delete a game container and all its data
    static func deleteGameContainer(for game: GameEntry) throws {
        let path = resolveGamePath(for: game)
        try FileManager.default.removeItem(atPath: path)
        print("[Sandbox] Deleted container for \(game.title)")
    }

    // MARK: - Helpers

    private static func documentsDirectory() -> String {
        NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first ?? "/tmp"
    }

    private static func directorySize(at path: String) -> Int64 {
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(atPath: path) else { return 0 }
        var total: Int64 = 0
        while let file = enumerator.nextObject() as? String {
            let fullPath = (path as NSString).appendingPathComponent(file)
            let attrs = try? fm.attributesOfItem(atPath: fullPath)
            total += (attrs?[.size] as? Int64) ?? 0
        }
        return total
    }
}
